# Server info
server:
  name: "API Gateway MCP"
  description: "Generic API gateway that wraps REST APIs as MCP tools"
  version: "1.0.0"

# Authentication
auth:
  token_env_var: "API_GATEWAY_TOKEN"  # Environment variable for the API token

# Tool definitions
tools:
  - name: "weather-lookup"
    description: "Get current weather information for a city"
    endpoint: "https://api.openweathermap.org/data/2.5/weather"
    method: "GET"
    timeout: 30
    query_params:
      q: "{{city}}"
      appid: "{{env:OPENWEATHER_API_KEY}}"
      units: "metric"
    parameters:
      city:
        type: "string"
        description: "Name of the city to get weather for"
        required: true
